@baseUrl=http://localhost:3056/v1/api/carts

### Get cart
GET {{baseUrl}}?userId=1001
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

### Add to cart
POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "userId": "1001",
  "product": {
    "productId": "69cfec6ca43bb352916246b2",
    "shopId": "69c3b9aba22c7939928c963f",
    "name": "New jeanssssssss",
    "price": 50,
    "quantity": 5
  }
}

# {
#   "userId": "1001",
#   "product": {
#     "productId": "69d0095fc2305ae916641efc",
#     "shopId": "69c3b9aba22c7939928c963f",
#     "name": "New jeans",
#     "price": 50,
#     "quantity": 5
#   }
# }

### Update product quantity
POST {{baseUrl}}/update-product
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "userId": "1001",
  "cartOrders": [
    {
      "products": [
        {
          "shopId": "69c3b9aba22c7939928c963f",
          "productId": "69d0095fc2305ae916641efc",
          "price": 50,
          "quantity": 4,
          "oldQuantity": 12
        }
      ],
      "version": 1
    }
  ]
}

### Delete product
DELETE {{baseUrl}}/delete-product
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "userId": "1001",
  "productId": "69d0095fc2305ae916641efc"
}