@baseUrl=http://localhost:3056/v1/api

### Sign up
POST {{baseUrl}}/shop/signup
Content-Type: application/json
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026

{
  "name": "Shop tips",
  "email": "shoptipjs05@gmail.com",
  "password": "abc123"
}

### Login
POST {{baseUrl}}/shop/login
Content-Type: application/json
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026

{
  "email": "shoptipjs05@gmail.com",
  "password": "abc123",
  "refreshToken": ""
}

### Logout
POST {{baseUrl}}/shop/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDUwNzg4OSwiZXhwIjoxNzc0NjgwNjg5fQ.roONkdof1lXW3LMJJWLGDuFG6Nuw2e5ZKBQ5I_PcISuPvoqBy20v4qQOxFokO6hpG2dM97gnGvP8aJhXma4JNC5lwzoJtzvfUp1p4ybXsZVLIQkcf2mOnsxcRdiZUXQPt9Eo_By6s-Ie5s0HydZm7k4-WcqJmGjK28PrZlr1pw4BN4nB1PHxNZCVDW_Onht_PkwGQeP27dgYAZ5vsRVHpMgFBfZu1t87lNgPCyNJ_OMFJDnCNLJ1_R1popo1IbWfOQ0D2K3ucIHkULYT_1KRQ6P3w73iT8-syA9nrvNIf2TXUfI35KDmH_5GRjQTS7in8aqUQol4Nnw4yoRNHZh-KfAxiXNodRpU3cgigVg-1OsUppG9zHqes_PBcj_AreCKn7IGtp0oAm5Znt1w8XRGYuLZ4ivrpOeOUx5IT4lzHtgDxYtBl_HZ3qxcUNHsBttLwEjbMXbMqQSZtS2O_azMGyfQJGJYeSsCYP0pw2wXeHkRifw-b-FvYG4IksL2N7HItt-Ru_cGPmtmUV1xyKELd3rHRxvSJmkqmAVPf2c1WqV8qAKqLgKtPP_ujpKDkS9RHv2SG7SIOweyxPHIy2fkU4aHyNiWFTG-kcLe2_c-w0fsV8_mklbpOODVPMftAO-t1cAKdGjkjTPwEG6rzftPOTvG7Fbf_JFvziBo9VJXsYo
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

### Refresh token
POST {{baseUrl}}/shop/handle-refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDUxNDk5NSwiZXhwIjoxNzc0Njg3Nzk1fQ.hCDsL0ksBtn86YqZEV2EaI0ZqfQ5E3OMyfbk9OAQTytb0Jiv8FWZ92M8WnnvJO7wxQFVv1a3xxd_5FIO92imYKyBETjgzLcWuGPSgRcSk1LkjhmJt0cnj8ldz46zf5RApqzwSPK_RQgimFBofPxpdSxxwG0Po5eapsdf4KkRzkr40Z98XO9b476uE-QmXN_rPUdxgjTMRH8axkPFjNSwlua3qOHTsHGA7f7tv0uEIn6Ez4MNdx5uldg1uG6lLeUm-rKu0GI-AQWNcQZigIBKvaPoLMFodqSPypNR4AmiJ661YgH26qcQaV3e4opAdmkRDYD0UmyBNDR9TmVsxpYGeWMOJXmi1-NkG3-TMb0ipdwRP3M5fgesqvACQ34m5Pkwe4OhjIAS5ETT_wNg9oeofwK5nBNdcMJqdqdw6WyrQJHwOp04r0ys9_FD1kFiDmh23f4Y3mnzdqqNajzkCMIQPntAL98duCJjosVDOd7T3XkeScaePgYq-KuDr2AplUwdKySjONzpt7JcXbIVlnsG-s5wGpFP6pNykhsnl_cSmuTrftiTcBeLeIFb_-093jRCmtwb2ktwZLJYvFQxgsf3EfDp5M85i7tOk4hUhr99j8PSeK-kEGzQcE_67uprK06ikb6Vdo4pnDuHxGohZ8i_GAoLuy8WDmf1bFk6Q1DsfqQ
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDUxNDk5NSwiZXhwIjoxNzc1MTE5Nzk1fQ.i-l0-Fh_WyA9-b7BRUCK0Urfj-me_WPk3K9y_okqV7-_cyaNJPW8X82iThBs4r59Rq_cL-jIJJuggl8PsDjNY-_VCC0YP2IsguMXHesiP4_q0aPOuA1mVeplpww_VhHvmX6UdO09QSyGpDOaK68vDF0gYTuLJ0Zh5BLF0HZqtI2ucshO_FWZxrhQImXisT0G3M22VikfuWFB31AGlce6UIQCe83nfHXX84Arl8Wk1FURX7nvmGltN6zisBTuXGS3y3ygTe7zQzJl_x4d9INoxlb7pNmxoPs7hMAOir3gJY9c4AF-GKKwZCAcx34V6XCRbb1BSBAH9XCKTEnTw8lVeZZ9zFyGzulie1R45ycjvIWTF8IioRJtDUFwM-VRrdGjpooZMbehev9-8ZODpSYMtidp_9JQQ77xTBbDgRGNaIZUQaCNFPrZmPEBIqDT6B_oBti7Tr7Y7tEkbxOjHL-Zd0YEgoL9lmb00W3IoZgjdEHVJYjbciXCYjlCvgaxc82f52TL0FuOw_1OyImE9Umw_zBtDECTkdR83ypJfDcFlD2kyUWmmueJ4FBs1WTsEKV38VhAAaU0np88bkrJ7h-Dw1M7vTceKYmddYZYvj39znUr3rTsH5RInMaZZiOGAZPdElAPAmEbnGxMI5A5Ov3XrnQtXHjf65TwCznd3TYmuFI"
}

### JWT demo
GET {{baseUrl}}/list-users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0Iiwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3NDM1MzQ0OSwiZXhwIjoxNzc0MzczNDQ5fQ.NRdf_H0fM52NNJUyos0788m-89uz5SRZELGH6iB0I8C1Kg2Z2rsuZrO9aTX-bOCAkcNyRmD8mRu1WXWW_JCD00ZUyUw-6rxdqsYa7bvqZxFMVdkNEIhv1dX6RGID7e8OFcOIrES55V5HRzeOq12ASr2g-tokK8weyZ028wHh84_61zeMzyZEsJRwRWQwVV_PsO4PmSuu_x1G25q_vNjvwBWR8AuiW7NdunMA6Q41jdaXJE1wszpeY2egc8m9WDWyN9koqc6bQYfdSWwAH3I_xGb6a2ogJOsmZ3fqlhCo6k5NWd0uiO5ElPnepJnjLqVjGEa1Gq6JjRE-CqF5bY5J-PzBzxtALQhwvgWHQaWfVgecen5S-OjHnHvEwHKqTZ-bY9vx-Y0IwcICa9jJw0u4Ube5W_T4DFU-sT0beeV8QhrQiZ93TXMGkSrW2cwRhBB7wSHUsBDQNT69dGoXV76iJFOILg5QBZzby-0Hp3TJIwTcBJvUSC6Wi4RZ3FnJXVkk04jzONBK3jXvkC4fMHMi6uHuTp_-8e9AuJskMmCSAume78DHm68J18syKwH5JEAKsO4q8yVUjffJsKNq4GM1HZKLNRccQKeleJe-QUAiFDYXS_NOzKUbWPAVU3SYDLr3TBoBPgTRqNtgOu103KLLfaEoFtn8ftswXBd1Ybv3Ykw

### JWT demo
DELETE {{baseUrl}}/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0Iiwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NzQzNTM0NDksImV4cCI6MTc3NDk1ODI0OX0.htF8ySBasIFPKPWyWjavYYLiQCBPLvCwyjkeKBXGFMd_7UOhpsWIJD51fw6cPK9Df9r_tIXxdBGSAzaGnf10hzwouwHq6MqpvIKpEI5lWIwN90Bg756UgVKu5a5X2gX0sCkAE83IXwp3upj8j1IpFGRDMpQM_ZHyA4bBMnz7Vp9vwmp2UYi5NHNf45CbCEm-caR6YhG03mjBcO0xgzqfqw1yMaNs-cd9IbGHe-WxAxFhdH453b4b5Ik6LQDyYIZlB1a8Y7GXgHXugvacGCBDf4JCPwbn7_ctedd1rF4GM3yhXNSO46gb2ewt6kiZ626XmZ_7WwztcPTT7lf6iDTWPxGn0oUts2WOaRA7qMiUbX7B4g5rmfpbHGI6YkN4pr0gF0kyzLb-1fUdyjLk1NXSdcByAOvQWIFxwwr1nf_zvQRitMaVmiisuqx_oDW-8_3MSjJQUOqWoxL0Bj1yV5qTQ7hUH8fSptKaWIVKkUmPlj-VsD4R8Nc33RLn8ATjsSWWf69jsqC5EuKzuTcfj5WuCNxjQFGUNjvxt1J-HYIcUwlaD_rwh2LCrhb44YEYCL8EmsWxyN0Ztx423223TbJVD9kd3gnLpwC9fi2mg-TEktypvkqvJylkCDzCjHlcUKxGLrBPrqK13JfW8hrb8gsDH5FtMdowu9G5IzHGBycdTtk"
}

### JWT demo
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0Iiwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NzQzNTIxNjMsImV4cCI6MTc3NDk1Njk2M30.S_dqihfAd_y5s3eGQu5lLoNbp_QvjhgEnKTAVIpSbWvecFLg7LdQCOGGYI8aFmTd4cdIqLNwecWru8RV1_HQLcvatKMPKdKLGb6T1vfuscaUgOvGJwBHvlVK6ZvrpBmhkjeyw4Yy0VfQGkgegY7U7_Fq1JngzL1oNETkA9qrX7P6zYuozRk_1PLYtiqc5OhsL2K6JDZLdJK0vRtgsjTsBfunX4I40VBqtyq_4HjpEhe9-rn0Duw4NXmUH5oKmrndAPr-H0NhlJ3ircF3y_obfbuc6jDgbVDNvP2BGSQ2mRRYN6xpB3qM_Ez7V2Le-1kqRh5g6Jl-cuIGxuwoB2_amdQFUHiM4iv5an4UjJm1XtxBEm4sbDdAsoWr-ss6lUE4m7_DK-v8LJyMQsGO4EGjI2X9J77k9Cb5VAw3GUIGmVi-MrfT4hpKmYOmmaDBgSxmOaqA42tuviRa8SXtoVjBm9xXMbXQ70WqD6AMaAPXf8BTR5UbC56Wwf9T3tL56A8bWiGTsDtl9_RAOhNXKzUrvB2TZi-wuuK5XG7aTskOeKDN_9n-nv-uWH_ufg_Yff1R1cHW2vMxKc643-Cim8tQWuljw6klcaRiZ91fbjojuygGlZ8EZzKNzoFXXIwW-2KtYkQlv40nMIucYvqb8S5Tq0zrgMd7g4wsGeQwAW_YWc8"
}