@baseUrl=http://localhost:3056/v1/api

### Sign up
POST {{baseUrl}}/shop/signup
Content-Type: application/json
x-api-key: {{$dotenv X_API_KEY}}

{
  "name": "Shop tips",
  "email": "shoptipjs05@gmail.com",
  "password": "abc123"
}

### Login
POST {{baseUrl}}/shop/login
Content-Type: application/json
x-api-key: {{$dotenv X_API_KEY}}

{
  "email": "shoptipjs03@gmail.com",
  "password": "abc123",
  "refreshToken": ""
}

### Logout
POST {{baseUrl}}/shop/logout
Content-Type: application/json
authoro
x-api-key: {{$dotenv X_API_KEY}}
x-client-id: {{$dotenv X_CLIENT_ID}}

### Refresh token
POST {{baseUrl}}/shop/handle-refresh-token
Content-Type: application/json
x-api-key: {{$dotenv X_API_KEY}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDUyMjc2MCwiZXhwIjoxNzc1MTI3NTYwfQ.pJ3zQP6XmIzzGfTw1oxZEN8F0h3FPGMUvdtN2AijFXDl1Q-EenCEHeY8_PCsyxe-RU4dpHDcsjrfercu2BlUDUnIIcuVUm1RJW-HXOTleleKzUoe6by8c6BtLL8F-5b1V_eqG9ZRHllfmgPW4IHfg3RhVwRLZWsN3fSKAlEPSP7ROqQ9Vzm4M4yTJ1RH_pG5WumLG3foDK-_Cdziw9o5x0K0WvQtGKW4Bms0hMH_cUQoTzJeGebgYDlnhiUJ1vH481kJrp95JCnNRtrNVcOedvW67or6J4pMlvWyka4VLXOuCtqqcNWQgrywGOUBF2RwBm8_e0WgXENstr3N4E4ZXWDdmJ4cJg9VTo0-DpH5Eiru9aAyXOWbJGKzgpcJQMQGu0mOGge5XZNUcE9G5tX5U0GYB9q365WghscmO33BGJdbtrzxyVvl_0i6umCpcy7IBi2LRyeerRXPJd1rRQdqeHOoINgzvo5fEWnT9gpXlero291bFO_cVAqDu9NGyLXwLgGZgwarZEyTWNZXIZ4y-rTk8nlYgucUR_jwHBZya5Z0os9TX0qyBqz9vX50UlnfUXLHF_H4OcvetY84vgls6XelDep3PF0mGimP78VwbFHviQjGOcRHShZkRuWrcFxEj8zwhXVNTtfTRhZ82C1T528hh9tQ_BYh3b7kU51p-GI

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDUyMjc2MCwiZXhwIjoxNzc1MTI3NTYwfQ.pJ3zQP6XmIzzGfTw1oxZEN8F0h3FPGMUvdtN2AijFXDl1Q-EenCEHeY8_PCsyxe-RU4dpHDcsjrfercu2BlUDUnIIcuVUm1RJW-HXOTleleKzUoe6by8c6BtLL8F-5b1V_eqG9ZRHllfmgPW4IHfg3RhVwRLZWsN3fSKAlEPSP7ROqQ9Vzm4M4yTJ1RH_pG5WumLG3foDK-_Cdziw9o5x0K0WvQtGKW4Bms0hMH_cUQoTzJeGebgYDlnhiUJ1vH481kJrp95JCnNRtrNVcOedvW67or6J4pMlvWyka4VLXOuCtqqcNWQgrywGOUBF2RwBm8_e0WgXENstr3N4E4ZXWDdmJ4cJg9VTo0-DpH5Eiru9aAyXOWbJGKzgpcJQMQGu0mOGge5XZNUcE9G5tX5U0GYB9q365WghscmO33BGJdbtrzxyVvl_0i6umCpcy7IBi2LRyeerRXPJd1rRQdqeHOoINgzvo5fEWnT9gpXlero291bFO_cVAqDu9NGyLXwLgGZgwarZEyTWNZXIZ4y-rTk8nlYgucUR_jwHBZya5Z0os9TX0qyBqz9vX50UlnfUXLHF_H4OcvetY84vgls6XelDep3PF0mGimP78VwbFHviQjGOcRHShZkRuWrcFxEj8zwhXVNTtfTRhZ82C1T528hh9tQ_BYh3b7kU51p-GI"
}

### JWT demo
DELETE {{baseUrl}}/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0Iiwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NzQzNTM0NDksImV4cCI6MTc3NDk1ODI0OX0.htF8ySBasIFPKPWyWjavYYLiQCBPLvCwyjkeKBXGFMd_7UOhpsWIJD51fw6cPK9Df9r_tIXxdBGSAzaGnf10hzwouwHq6MqpvIKpEI5lWIwN90Bg756UgVKu5a5X2gX0sCkAE83IXwp3upj8j1IpFGRDMpQM_ZHyA4bBMnz7Vp9vwmp2UYi5NHNf45CbCEm-caR6YhG03mjBcO0xgzqfqw1yMaNs-cd9IbGHe-WxAxFhdH453b4b5Ik6LQDyYIZlB1a8Y7GXgHXugvacGCBDf4JCPwbn7_ctedd1rF4GM3yhXNSO46gb2ewt6kiZ626XmZ_7WwztcPTT7lf6iDTWPxGn0oUts2WOaRA7qMiUbX7B4g5rmfpbHGI6YkN4pr0gF0kyzLb-1fUdyjLk1NXSdcByAOvQWIFxwwr1nf_zvQRitMaVmiisuqx_oDW-8_3MSjJQUOqWoxL0Bj1yV5qTQ7hUH8fSptKaWIVKkUmPlj-VsD4R8Nc33RLn8ATjsSWWf69jsqC5EuKzuTcfj5WuCNxjQFGUNjvxt1J-HYIcUwlaD_rwh2LCrhb44YEYCL8EmsWxyN0Ztx423223TbJVD9kd3gnLpwC9fi2mg-TEktypvkqvJylkCDzCjHlcUKxGLrBPrqK13JfW8hrb8gsDH5FtMdowu9G5IzHGBycdTtk"
}
