@baseUrl=http://localhost:3056/v1/api/discounts

### Create discount
POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "name": "New discount for shop 03",
  "description": "New discount description",
  "type": "percentage",
  "value": 20,
  "code": "SHOP-1155",
  "startDate": "2026-04-04 09:00:00",
  "endDate": "2026-04-20 09:00:00",
  "maxUses": 100,
  "maxUsesPerUser": 1,
  "minOrderValue": 100000,
  "usesCount": 0,
  "usersUsed": [],
  "isActive": true,
  "appliesTo": "specific",
  "appliesToProduct": ["69d7b22815a9235e0ee4006c", "69d79d89b5e2578d08537e90"]
}

### Create discount
POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "name": "New discount",
  "description": "New discount description",
  "type": "percentage",
  "value": 10,
  "code": "SHOP-1122",
  "startDate": "2026-04-04 09:00:00",
  "endDate": "2026-04-20 09:00:00",
  "maxUses": 100,
  "maxUsesPerUser": 1,
  "minOrderValue": 100000,
  "usesCount": 0,
  "usersUsed": [],
  "isActive": true,
  "appliesTo": "specific",
  "appliesToProduct": ["69d0095fc2305ae916641efc", "69cfec6ca43bb352916246b2"]
}

### Get all discounts for shop
GET {{baseUrl}}/
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

### Delete discount
DELETE {{baseUrl}}/
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "code": "SHOP-1133"
}

### Get products with code
GET {{baseUrl}}/list-products?shopId=69c3b6ce0c5ac39c2105ebe0&code=SHOP-1155&limit=10&page=1
x-api-key: {{$dotenv X_API_KEY}}

### Get amount
POST {{baseUrl}}/amount
Content-Type: application/json
x-api-key: {{$dotenv X_API_KEY}}

{
  "shopId": "69c3b9aba22c7939928c963f",
  "userId": 2,
  "code": "SHOP-1133",
  "products": [
    {
      "productId": "69d0095fc2305ae916641efc",
      "quantity": 5,
      "price": 120000
    }
  ]
}