@baseUrl=http://localhost:3056/v1/api/products

### Create product
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDg2NzQxOSwiZXhwIjoxNzc1MDQwMjE5fQ.EJWlA0rVA0nWVFw4yvce-HgidA0YMWtom2CS-wjFb4WpIABHAZZH4f1zjribP0g2D5wb3iU4pJ8pnbiYiDYYGmqilcYLZP5ihRPgUKnCqZSGJb0U14lZx8PCNrA5s6Wb_1lwljLoaRPkZAUnuhCQNWqcGOZBPfz3z9i7aCLOub6GIHaB748wJQhpaMjrbtDk2d-h8ulq6OhSJgmx7jjIzsubjTWgIg1wGbY_dAdgYORRKKdRlg6-EUdiM2JVzmVUjIn67NkB13Ubu3TvmkO7jtmVp8ceqdVgYbnHdJaJaUsGuG7uLjJWgyCveaY4-936rFir8pz66Kcqebn9iXE3-O2tbUfVHLXki2gREFQNbu6rqdAnod0qYmGtwf0vR2ORTgJPPiteCS1DOablIrw0A4judbuwsuSXAq-8qxQnD3jg3zx3xKDEseKIOBm0b5uZKInVAHhMgG0ofvJPv4v0XCo3hRh8r84OC-fVsmOvQ_wfn0I3itOPhNuJCTGO83QGjDKXwhW1Z9CLlJ-Lu7_xO--efvwe3Mu4k2_3hOG_dre2deGitn8hvZcbVWxRu-pANOlmx6tvusk7hsEee2UQgB12lh9H9v6plqJKtc1K4973fC0fSed7QUAX5eeBdFKEfDMpnkMeR_RKBC7A0WImffcgbO6S1Eveiky-3aUnaxY
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

{
  "product_name": "New jeans",
  "product_thumb": "high-quality thumb jeans",
  "product_description": "High quality thumb jeans",
  "product_price": 50,
  "product_quantity": 5,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "Levis",
    "size": "L",
    "material": "Denim"
  }
}

### Get all draft products by shop id
GET {{baseUrl}}/drafts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDg2NzQxOSwiZXhwIjoxNzc1MDQwMjE5fQ.EJWlA0rVA0nWVFw4yvce-HgidA0YMWtom2CS-wjFb4WpIABHAZZH4f1zjribP0g2D5wb3iU4pJ8pnbiYiDYYGmqilcYLZP5ihRPgUKnCqZSGJb0U14lZx8PCNrA5s6Wb_1lwljLoaRPkZAUnuhCQNWqcGOZBPfz3z9i7aCLOub6GIHaB748wJQhpaMjrbtDk2d-h8ulq6OhSJgmx7jjIzsubjTWgIg1wGbY_dAdgYORRKKdRlg6-EUdiM2JVzmVUjIn67NkB13Ubu3TvmkO7jtmVp8ceqdVgYbnHdJaJaUsGuG7uLjJWgyCveaY4-936rFir8pz66Kcqebn9iXE3-O2tbUfVHLXki2gREFQNbu6rqdAnod0qYmGtwf0vR2ORTgJPPiteCS1DOablIrw0A4judbuwsuSXAq-8qxQnD3jg3zx3xKDEseKIOBm0b5uZKInVAHhMgG0ofvJPv4v0XCo3hRh8r84OC-fVsmOvQ_wfn0I3itOPhNuJCTGO83QGjDKXwhW1Z9CLlJ-Lu7_xO--efvwe3Mu4k2_3hOG_dre2deGitn8hvZcbVWxRu-pANOlmx6tvusk7hsEee2UQgB12lh9H9v6plqJKtc1K4973fC0fSed7QUAX5eeBdFKEfDMpnkMeR_RKBC7A0WImffcgbO6S1Eveiky-3aUnaxY
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

### Get all published products by shop id
GET {{baseUrl}}/published
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDg2NzQxOSwiZXhwIjoxNzc1MDQwMjE5fQ.EJWlA0rVA0nWVFw4yvce-HgidA0YMWtom2CS-wjFb4WpIABHAZZH4f1zjribP0g2D5wb3iU4pJ8pnbiYiDYYGmqilcYLZP5ihRPgUKnCqZSGJb0U14lZx8PCNrA5s6Wb_1lwljLoaRPkZAUnuhCQNWqcGOZBPfz3z9i7aCLOub6GIHaB748wJQhpaMjrbtDk2d-h8ulq6OhSJgmx7jjIzsubjTWgIg1wGbY_dAdgYORRKKdRlg6-EUdiM2JVzmVUjIn67NkB13Ubu3TvmkO7jtmVp8ceqdVgYbnHdJaJaUsGuG7uLjJWgyCveaY4-936rFir8pz66Kcqebn9iXE3-O2tbUfVHLXki2gREFQNbu6rqdAnod0qYmGtwf0vR2ORTgJPPiteCS1DOablIrw0A4judbuwsuSXAq-8qxQnD3jg3zx3xKDEseKIOBm0b5uZKInVAHhMgG0ofvJPv4v0XCo3hRh8r84OC-fVsmOvQ_wfn0I3itOPhNuJCTGO83QGjDKXwhW1Z9CLlJ-Lu7_xO--efvwe3Mu4k2_3hOG_dre2deGitn8hvZcbVWxRu-pANOlmx6tvusk7hsEee2UQgB12lh9H9v6plqJKtc1K4973fC0fSed7QUAX5eeBdFKEfDMpnkMeR_RKBC7A0WImffcgbO6S1Eveiky-3aUnaxY
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

### Publish product by shop id
POST  {{baseUrl}}/publish/69ca5c7504a3accaab9a4608
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDg2NzQxOSwiZXhwIjoxNzc1MDQwMjE5fQ.EJWlA0rVA0nWVFw4yvce-HgidA0YMWtom2CS-wjFb4WpIABHAZZH4f1zjribP0g2D5wb3iU4pJ8pnbiYiDYYGmqilcYLZP5ihRPgUKnCqZSGJb0U14lZx8PCNrA5s6Wb_1lwljLoaRPkZAUnuhCQNWqcGOZBPfz3z9i7aCLOub6GIHaB748wJQhpaMjrbtDk2d-h8ulq6OhSJgmx7jjIzsubjTWgIg1wGbY_dAdgYORRKKdRlg6-EUdiM2JVzmVUjIn67NkB13Ubu3TvmkO7jtmVp8ceqdVgYbnHdJaJaUsGuG7uLjJWgyCveaY4-936rFir8pz66Kcqebn9iXE3-O2tbUfVHLXki2gREFQNbu6rqdAnod0qYmGtwf0vR2ORTgJPPiteCS1DOablIrw0A4judbuwsuSXAq-8qxQnD3jg3zx3xKDEseKIOBm0b5uZKInVAHhMgG0ofvJPv4v0XCo3hRh8r84OC-fVsmOvQ_wfn0I3itOPhNuJCTGO83QGjDKXwhW1Z9CLlJ-Lu7_xO--efvwe3Mu4k2_3hOG_dre2deGitn8hvZcbVWxRu-pANOlmx6tvusk7hsEee2UQgB12lh9H9v6plqJKtc1K4973fC0fSed7QUAX5eeBdFKEfDMpnkMeR_RKBC7A0WImffcgbO6S1Eveiky-3aUnaxY
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

### Unpublish product by shop id
POST  {{baseUrl}}/unpublish/69ca5c7504a3accaab9a4608
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDg2NzQxOSwiZXhwIjoxNzc1MDQwMjE5fQ.EJWlA0rVA0nWVFw4yvce-HgidA0YMWtom2CS-wjFb4WpIABHAZZH4f1zjribP0g2D5wb3iU4pJ8pnbiYiDYYGmqilcYLZP5ihRPgUKnCqZSGJb0U14lZx8PCNrA5s6Wb_1lwljLoaRPkZAUnuhCQNWqcGOZBPfz3z9i7aCLOub6GIHaB748wJQhpaMjrbtDk2d-h8ulq6OhSJgmx7jjIzsubjTWgIg1wGbY_dAdgYORRKKdRlg6-EUdiM2JVzmVUjIn67NkB13Ubu3TvmkO7jtmVp8ceqdVgYbnHdJaJaUsGuG7uLjJWgyCveaY4-936rFir8pz66Kcqebn9iXE3-O2tbUfVHLXki2gREFQNbu6rqdAnod0qYmGtwf0vR2ORTgJPPiteCS1DOablIrw0A4judbuwsuSXAq-8qxQnD3jg3zx3xKDEseKIOBm0b5uZKInVAHhMgG0ofvJPv4v0XCo3hRh8r84OC-fVsmOvQ_wfn0I3itOPhNuJCTGO83QGjDKXwhW1Z9CLlJ-Lu7_xO--efvwe3Mu4k2_3hOG_dre2deGitn8hvZcbVWxRu-pANOlmx6tvusk7hsEee2UQgB12lh9H9v6plqJKtc1K4973fC0fSed7QUAX5eeBdFKEfDMpnkMeR_RKBC7A0WImffcgbO6S1Eveiky-3aUnaxY
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

### Search products
GET  {{baseUrl}}/search/new jeans
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026