@baseUrl=http://localhost:3056/v1/api/products

### Create product
POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "name": "New jeans shop 03",
  "thumbnail": "high-quality thumb jeans",
  "description": "High quality thumb jeans",
  "price": 500000,
  "quantity": 10,
  "type": "Clothing",
  "attributes": {
    "brand": "Levis",
    "size": "L",
    "material": "Denim"
  }
}

### Update product
PATCH {{baseUrl}}/69d79d89b5e2578d08537e90
Content-Type: application/json
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

{
  "name": "New jeans 03",
  "price": 150000,
  "type": "Clothing",
  "attributes": {
    "brand": "Levis 00001",
    "size": null
  }
}

### Search products
GET  {{baseUrl}}/search/new jeans
x-api-key: {{$dotenv X_API_KEY}}

### Get all products
GET  {{baseUrl}}
x-api-key: {{$dotenv X_API_KEY}}

### Get product
GET  {{baseUrl}}/69cfb3791c16f1bdd978b643
x-api-key: {{$dotenv X_API_KEY}}

### Get all draft products by shop id
GET {{baseUrl}}/drafts
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

### Get all published products by shop id
GET {{baseUrl}}/published
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

### Publish product by shop id
POST  {{baseUrl}}/publish/69d78e5493e8c9afb404c57a
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}

### Unpublish product by shop id
POST  {{baseUrl}}/unpublish/69ca5c7504a3accaab9a4608
Authorization: {{$dotenv AUTH_TOKEN}}
x-client-id: {{$dotenv X_CLIENT_ID}}
x-api-key: {{$dotenv X_API_KEY}}
