@baseUrl=http://localhost:3056/v1/api

### Create product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2OWMzYjlhYmEyMmM3OTM5OTI4Yzk2M2YiLCJlbWFpbCI6InNob3B0aXBqczA1QGdtYWlsLmNvbSIsImlhdCI6MTc3NDY3MDMwOCwiZXhwIjoxNzc0ODQzMTA4fQ.Bgj-vn_16QYTZTz1G1PeNTcM-r3LX6eC6uh763khE7EgzKVeo9Zzhnp7Wz5TBR-1QdXgOPCxilIp3bfuQJW3JYLxH6OGkeyakZu47eEgij4ITby2angjiHsmmydlbmPfKiLfrJyVJNuJSP9TWZq9Kap6DSkFp27G-GapMG0WX8HEtMBRJasxcdhdM5gq-WyCoqOlxNpCuZJmkK5oJIPvFcnUUnbv55_ooW5rhapD34kZvVY_fCGTWdKdYQHW3l-EZMydaf_O6-y-csb1IqqPdLtaxs_ATrVp2vm75zKmy9cxrdV1idgFYR8C4OWp5HtkwEfsGc9i7uHhPG4f73j4fHva8_7StsqlqQXAZNP1HuSB88zTnwpLOtj9qoV_1v_Lc9lg5qTstzUWuWeWmJlikI7PxpxNk2_s9aBYOjvKoMlmhUpeGfhK8BM6mvNK2hQgW4FGh3GT-bKs7PI3uxgmANTZkW2elKe4J51hsVyECu-9jg9DVS3ltVtmUdNYCg8LYcJj9O-dBh9sJRXjxL93Tt80yomgx19jHjF5PEMwF2jxD91PCIllGXINtzkD2Dy85QIAWWk6v1iOOERDVanfZWDFOoqVDUcZyi1PENfLSJa0VMhBl0NhZMB7aUYebzWYmb2k_-k4n39h_Z5m17IpPvGPvGmbr_OB60ueq44FJhE
x-api-key: 3a07e364bdae7a7f44adc398e3c78388f06835be51d88b07904af7d293c8a5dffbdb5c5aa4e90a85214dbb98a09ce1e9f9032d4fea62fcaa9bac44dc2f915026
x-client-id: 69c3b9aba22c7939928c963f

{
  "product_name": "New jeans",
  "product_thumb": "high-quality thumb jeans",
  "product_description": "High quality thumb jeans",
  "product_price": 50,
  "product_quantity": 5,
  "product_type": "Clothing",
  "product_attributes": {
    "brand": "Levis",
    "size": "L",
    "material": "Denim"
  }
}